server:
  port: 12002
spring:
  application:
    name: topic-course-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://cdb-6op2eovc.cd.tencentcdb.com:10063/dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: aaBBcJ123456qwe
      min-idle: 1
      initial-size: 1
      max-active: 5
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
      filters: stat
  cloud:
    nacos:
      discovery:
        server-addr: 119.29.164.252:8848
        username: nacos
        password: nacos
        namespace: yjlan
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000

dubbo:
  registry:
    address: nacos://119.29.164.252:8848
  protocol:
    name: dubbo
    port: 28085
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
  cloud:
    subscribed-services: topic-course-service
  scan:
    base-packages: com.grab.degree.topic.course.api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

